#' Read output file from QuIBL
#'
#' This function reads in the basic output generated by a QuIBL run
#' @param filepath QuIBL output file
#' @export
#' @examples
#' read.csv.quibl(quiblFile.csv)

read_csv_quibl <- function(filepath){
  utils::read.csv(filepath,header=T,
           colClasses = c(rep("factor",2),rep("numeric",9)))
}

#' Read species tree
#'
#' This function is just the ape read tree function
#' @param filepath species tree in newick format
#' @export
#' @examples
#' read.csv.quibl(speciesTree.nwk)

read_speciesTree <- function(filepath){
  ape::read.tree(filepath)
}

